fix: update package lock (#151)
The getting started flow was failing due to
`2024-10-11T17:39:05Z: #21 1.963 Error: Cannot find module
@rollup/rollup-linux-x64-gnu. npm has a bug related to optional
dependencies (https://github.com/npm/cli/issues/4828). Please try npm i
again after removing both package-lock.json and node_modules directory.`